//! SPIKE: prove flowlog-rs can be driven LIVE / incrementally in-process.
//!
//! The generated module (from build.rs compiling path.dl in DatalogInc mode)
//! defines, at the include site (re-exported from an inner `__flowlog_gen`):
//!   - `pub struct DatalogIncrementalEngine { ... }`
//!       fn new(workers: usize) -> Self          // spawns timely workers on a thread
//!       fn begin(&mut self)                      // (auto-called by first insert_*)
//!       fn insert_<rel>(&mut self, items: Vec<rel::<Pascal>>)
//!       fn remove_<rel>(&mut self, items: Vec<rel::<Pascal>>)   // retraction (diff -1)
//!       fn abort(&mut self)
//!       fn commit(&mut self) -> IncrementalResults              // runs ONE epoch to fixpoint, blocks
//!   - `pub mod rel { pub type Edge = (i32, i32); pub type Path = (i32, i32); }`
//!     (TUPLE ALIASES, not named-field structs — confirmed from
//!     flowlog-build/src/build/relation/user.rs)
//!   - `pub struct IncrementalResults { pub path: Vec<(rel::Path, i32)>, ... }`
//!     (field name = rust_ident(rel.name()); relation names are normalized
//!     lowercase by the parser, matching flowlog's own lib-mode test runner.)
//!
//! commit() barriers twice (release workers -> compute to fixpoint -> resync),
//! so it returns only AFTER this epoch's fixpoint, carrying the epoch's deltas.
//! The engine does NOT fold across commits, so we (the host) maintain a snapshot
//! of `Path` by applying the (tuple, diff) deltas into a HashMap<tuple, count>.
//! This is exactly PLAN.md §4 design (A): a Rust-side materialized mirror.

include!(concat!(env!("OUT_DIR"), "/path.rs")); // generated by flowlog-build

use std::collections::HashMap;

/// Host-side mirror: fold per-epoch deltas into a live snapshot of `Path`.
#[derive(Default)]
struct Mirror {
    counts: HashMap<(i32, i32), i64>,
}
impl Mirror {
    fn apply(&mut self, deltas: &[(rel::Path, i32)]) {
        // rel::Path is the tuple alias (i32, i32); read positionally.
        for (t, d) in deltas {
            let key = (t.0, t.1);
            let e = self.counts.entry(key).or_insert(0);
            *e += *d as i64;
            if *e == 0 {
                self.counts.remove(&key);
            }
        }
    }
    fn live(&self) -> Vec<(i32, i32)> {
        let mut v: Vec<_> = self
            .counts
            .iter()
            .filter(|(_, c)| **c > 0)
            .map(|(k, _)| *k)
            .collect();
        v.sort();
        v
    }
}

fn edge(x: i32, y: i32) -> rel::Edge {
    (x, y)
}

fn main() {
    let mut engine = DatalogIncrementalEngine::new(1);
    let mut mirror = Mirror::default();

    // ---- Epoch 1: insert a chain 1->2->3, run to fixpoint, READ Path back ----
    engine.insert_edge(vec![edge(1, 2), edge(2, 3)]);
    let r = engine.commit();
    mirror.apply(&r.path);
    println!("after epoch 1 (edges 1-2, 2-3):");
    println!("  Path = {:?}", mirror.live());
    // expect: [(1,2),(1,3),(2,3)]

    // ---- Epoch 2: insert MORE edges live (3->4), step AGAIN, read updated Path ----
    engine.insert_edge(vec![edge(3, 4)]);
    let r = engine.commit();
    mirror.apply(&r.path);
    println!("after epoch 2 (added 3-4):");
    println!("  Path = {:?}", mirror.live());
    // expect: [(1,2),(1,3),(1,4),(2,3),(2,4),(3,4)]

    // ---- Epoch 3: RETRACT an edge (remove 2->3), step, read shrunken Path ----
    engine.remove_edge(vec![edge(2, 3)]);
    let r = engine.commit();
    mirror.apply(&r.path);
    println!("after epoch 3 (retract 2-3):");
    println!("  Path = {:?}", mirror.live());
    // expect: 1->2, 3->4 survive; everything through 2->3 (1-3,1-4,2-3,2-4) gone
    // i.e. [(1,2),(3,4)]

    println!("\nLIVE INCREMENTAL FEED + STEP + READ (+ retraction): PROVEN");
}
